from datetime import UTC, datetime

from agenttrace.detectors.benign import detect_benign_automation
from agenttrace.models import Observation, Provenance


def make(actor: str, event_id: str, text: str, actor_type: str | None = None) -> Observation:
    now = datetime.now(UTC)
    return Observation(
        source="test",
        source_event_id=event_id,
        observed_at=now,
        event_time=now,
        actor=actor,
        event_type="comment",
        text=text,
        metadata={"actor_type": actor_type},
        provenance=Provenance(url=f"https://example.test/{event_id}"),
    )


def test_human_build_and_deploy_text_is_not_benign_automation():
    assert detect_benign_automation([make("alice", "1", "Please build and deploy this")]) == []


def test_unknown_bot_identity_alone_is_not_suppressed():
    assert detect_benign_automation([make("novel-agent[bot]", "1", "task_id=work-9217")]) == []


def test_human_routine_text_and_unrelated_bot_identity_do_not_form_composite():
    observations = [
        make("alice", "1", "Build release notes for v1.2.3"),
        make("novel-agent[bot]", "2", "ACK task_id=work-9217", "Bot"),
    ]
    assert detect_benign_automation(observations) == []


def test_bot_plus_routine_workflow_is_penalized():
    observations = [
        make("renovate[bot]", "1", "Bump dependency httpx to 1.2.3", "Bot"),
        make("renovate[bot]", "2", "Automated update generated by Renovate", "Bot"),
    ]
    signals = detect_benign_automation(observations)
    assert signals
    assert signals[0].score >= 0.80


def test_auto_generated_bot_comment_is_a_routine_composite():
    signals = detect_benign_automation(
        [make("reviewer[bot]", "1", "Auto-generated review report", "Bot")]
    )
    assert signals
