from __future__ import annotations

import re
from collections import Counter

from agenttrace.models import Observation, Signal

BOT_IDENTITY_RE = re.compile(
    r"(?:\[bot\]$|(?:^|[-_])(?:bot|ci)(?:$|[-_])|(?:automation|renovate|dependabot))",
    re.IGNORECASE,
)
ROUTINE_EVENT_TYPES = {
    "CheckRunEvent",
    "CheckSuiteEvent",
    "DeploymentEvent",
    "DeploymentStatusEvent",
    "ReleaseEvent",
}
ROUTINE_PATTERNS = (
    re.compile(r"\b(?:bump|update)\s+(?:dependency|dependencies|lockfile)\b", re.IGNORECASE),
    re.compile(r"\b(?:all checks? (?:passed|failed)|coverage (?:report|changed))\b", re.IGNORECASE),
    re.compile(
        r"\b(?:generated by|auto[- ]generated|do not edit|automated (?:release|update|merge))\b",
        re.IGNORECASE,
    ),
    re.compile(r"\b(?:release notes?|changelog)\b.*\bv?\d+\.\d+\.\d+\b", re.IGNORECASE),
)


def detect_benign_automation(observations: list[Observation]) -> list[Signal]:
    """Penalize composite routine workflows, not automation identities by themselves."""
    if not observations:
        return []
    bot_like = sum(1 for obs in observations if _bot_identity(obs))
    composite = [obs for obs in observations if _bot_identity(obs) and _routine_behavior(obs)]
    normalized = [
        _normalize_template(obs.text or "")
        for obs in observations
        if _bot_identity(obs) and obs.text
    ]
    repeated = sum(count for count in Counter(normalized).values() if count >= 2)

    bot_fraction = bot_like / len(observations)
    composite_fraction = len(composite) / len(observations)
    template_fraction = repeated / len(observations) if observations else 0.0
    if not composite:
        return []
    score = min(
        1.0,
        0.15 * bot_fraction + 0.75 * composite_fraction + 0.10 * template_fraction,
    )
    if score < 0.20:
        return []
    return [
        Signal(
            family="benign",
            name="routine_automation_fingerprint",
            score=score,
            observation_ids=[obs.event_key or obs.source_event_id for obs in observations],
            evidence=[
                f"bot_or_app_fraction={bot_fraction:.2f}",
                f"composite_routine_fraction={composite_fraction:.2f}",
                f"repeated_template_fraction={template_fraction:.2f}",
            ],
        )
    ]


def _bot_identity(observation: Observation) -> bool:
    actor_type = str(observation.metadata.get("actor_type") or "").lower()
    app_slug = observation.metadata.get("github_app_slug")
    return actor_type == "bot" or bool(app_slug) or bool(BOT_IDENTITY_RE.search(observation.actor))


def _routine_behavior(observation: Observation) -> bool:
    if observation.event_type in ROUTINE_EVENT_TYPES:
        return True
    text = observation.text or ""
    return any(pattern.search(text) for pattern in ROUTINE_PATTERNS)


def _normalize_template(text: str) -> str:
    lowered = text.lower()
    lowered = re.sub(r"https?://\S+", "<url>", lowered)
    lowered = re.sub(r"\b[0-9a-f]{7,64}\b", "<hash>", lowered)
    lowered = re.sub(r"\b\d+(?:\.\d+)*\b", "<number>", lowered)
    return " ".join(lowered.split())[:500]
